version: '3.8'



services:
  backend4:
    build:
      context: .
      dockerfile: Dockerfile3
    ports:
      - "8000:8080"


  backend1:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8081:8080"

  backend2:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "8082:8080"


  backend3:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "8083:8080"

  backend10:
    build:
      context: .
      dockerfile: Dockerfile4
    ports:
      - "8500:8080"



  # backend5:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile4
  #   ports:
  #     - "8000:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - backend10
      # - backend5
